vars:
  # where to clone Git repositories (should be external directory)
  - repos_dir: ~/example_repositories
  # list of Git repositories to clone, and their URLs
  - repos:
      - name: tensorflow
        url: https://github.com/tensorflow/tensorflow.git
  # repositories, and authors in those repositories, to analyze/annotate
  - authors:
      - repo: tensorflow
        nick: ezhulenev
        author: ezhulenev@google.com
      - repo: tensorflow
        nick: yong.tang
        author: yong.tang.github@outlook.com

stages:
  clone:
    foreach: ${repos}
    do:
      desc: 'Clone ${item.name} repository from ${item.url}'
      cmd:
        - >-
          if [ -d ${repos_dir}/${item.name} ]; then
             echo 'Repository ${item.name} already cloned, skipping';
          else
             git clone ${item.url} ${repos_dir}/${item.name};
          fi
        - echo ${item.url} >data/examples/${item.name}.url
      outs:
        - data/examples/${item.name}.url

  annotate:
    foreach: ${authors}
    do:
      desc: 'Generating annotations for ${item.nick} from-repo ${item.repo}'
      cmd: >-
        diff-annotate from-repo
        --output-dir=data/examples/annotations/${item.repo}/${item.nick}/
        ${repos_dir}/${item.repo}
        --author=${item.author}
      deps:
        - src/diffannotator/annotate.py
        - data/examples/${item.repo}.url
      outs:
        - data/examples/annotations/${item.repo}/${item.nick}/
