[build-system]
requires = ["setuptools>=62.6"]
build-backend = "setuptools.build_meta"

[project]
name = "diffannotator"
version = "0.1.0"
description = "Annotate files and lines of diffs (patches) with their purpose and type"
readme = "README.md"
keywords = [
  "msr",
  "mining-software-repositories",
  "code-analysis",
]
authors = [
  {name = "Mikołaj Fejzer", email = "mfejzer@mat.umk.pl"},
  {name = "Jakub Narębski", email = "jnareb@mat.umk.pl"},
  {name = "Piotr Przymus", email = "piotr.przymus@mat.umk.pl"},
  {name = "Krzysztof Stencel", email = "stencel@mimuw.edu.pl"}
]
maintainers = [
  {name = "Mikołaj Fejzer", email = "mfejzer@mat.umk.pl"},
  {name = "Jakub Narębski", email = "jnareb@mat.umk.pl"},
  {name = "Piotr Przymus", email = "piotr.przymus@mat.umk.pl"},
  {name = "Krzysztof Stencel", email = "stencel@mimuw.edu.pl"}
]
license = {text = "MIT license"}
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
requires-python = ">= 3.7"  # vermin --eval-annotations --backport typing --backport typing_extensions .
dynamic = ["dependencies", "optional-dependencies"]

[project.scripts]
diff-annotate = "diffannotator.annotate:app"
diff-gather-stats = "diffannotator.gather_data:app"

[project.urls]
bugs = "https://github.com/ncusi/python-diff-annotator/issues"
homepage = "https://github.com/ncusi/python-diff-annotator"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = {file = ["requirements-dev.txt"] }}

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.setuptools.packages.find]
where = ["src"]
